# Generated by Django 4.2.4 on 2023-11-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=70)),
                ('auther_name', models.CharField(max_length=70)),
                ('type_book', models.CharField(max_length=70)),
                ('details', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=80)),
                ('phone_number', models.IntegerField()),
                ('classs', models.CharField(max_length=70)),
                ('type', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.add')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
    ]
